# Values for Production environment
replicaCount: 2

image:
  tag: "0e49d48f92cd950d699ba4f3ac023941c6b887f6"

# ConfigMap and Secret are managed by Terraform
configMap:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
