# Values for Development environment
replicaCount: 1

image:
  tag: "latest"

configMap:
  enabled: true
  data:
    JWT_ACCESS_TTL_MS: "3600000"
    JWT_REFRESH_TTL_MS: "86400000"
    AWS_REGION: "ap-northeast-2"
    REDIS_PORT: "6379"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
