# Values for Production environment
replicaCount: 2

image:
  tag: "6186293fa940caa990ab0a24028c32cda8080310"

# ConfigMap and Secret are managed by Terraform
configMap:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
