# Values for Production environment
replicaCount: 2

image:
  tag: "00e11b2535d1ffb5f60287c961f234598c2efed8"

# ConfigMap and Secret are managed by Terraform
configMap:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
