# Values for Production environment
replicaCount: 2

image:
  tag: "40603a08003d116ab8941efe108d6eb0fe5b93f0"

# ConfigMap and Secret are managed by Terraform
configMap:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
