apiVersion: apps/v1
kind: Deployment
metadata:
  name: sf-backend-websocket
  labels:
    app: sf-backend-websocket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sf-backend-websocket
  template:
    metadata:
      labels:
        app: sf-backend-websocket
    spec:
      nodeSelector:
        role: backend
      containers:
        - name: sf-backend-websocket
          image: 613307913976.dkr.ecr.ap-northeast-2.amazonaws.com/sf-backend-websocket:b4b4348a445820ea262b44f847bcace41eaff8da
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: sf-backend-websocket-secrets