apiVersion: v1
kind: Service
metadata:
  name: sf-backend-websocket
  labels:
    app: sf-backend-websocket
spec:
  type: ClusterIP
  selector:
    app: sf-backend-websocket
  ports:
    - port: 8000
      targetPort: 8000
