apiVersion: v1
kind: Service
metadata:
  name: sensor-ws-svc
  namespace: default
spec:
  selector:
    app: sensor-ws
  ports:
    - protocol: TCP
      port: 80 # 서비스(내부) 포트
      targetPort: 8000 # 컨테이너(실제) 포트
  type: ClusterIP # Ingress를 쓸 거라면 ClusterIP면 충분합니다
