apiVersion: apps/v1
kind: Deployment
metadata:
  name: sf-backend-aws
  labels:
    app: sf-backend-aws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sf-backend-aws
  template:
    metadata:
      labels:
        app: sf-backend-aws
    spec:
      nodeSelector:
        role: backend
      serviceAccountName: sf-backend-aws-sa
      containers:
        - name: sf-backend-aws
          image: 613307913976.dkr.ecr.ap-northeast-2.amazonaws.com/sf-backend-aws:a3df7a796f8403fe343b465edeed36053a0b3cd8
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: sf-backend-aws-secrets
            - configMapRef:
                name: sf-backend-aws-config
                
