# Values for Production environment
replicaCount: 2

image:
  tag: "e0636a2e2d6f7ab4aaa79368a9ea098ca729e585"

# ConfigMap and Secret are managed by Terraform
configMap:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
