apiVersion: v1
kind: Service
metadata:
  name: sf-backend-glb
  labels:
    app: sf-backend-glb
spec:
  type: ClusterIP
  selector:
    app: sf-backend-glb
  ports:
    - port: 8081
      targetPort: 8081
