apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: factory-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # TLS 비활성화: ACM 미보유로 ssl-redirect 비활성화
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sf-backend
                port:
                  number: 8080
          - path: /glb
            pathType: Prefix
            backend:
              service:
                name: sf-backend-glb
                port:
                  number: 8081
