apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: factory-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sf-backend
                port:
                  number: 8080

          - path: /glb
            pathType: Prefix
            backend:
              service:
                name: sf-backend-glb
                port:
                  number: 8081
