apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: factory-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    # 👇 [중요] 헬스 체크 경로 추가
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sf-backend
                port:
                  number: 8080
          - path: /glb
            pathType: Prefix
            backend:
              service:
                name: sf-backend-glb
                port:
                  number: 8081
          # 👇 [중요] 여기가 빠져 있어서 연결이 안 되는 겁니다!
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: sensor-ws-svc
                port:
                  number: 8000
