apiVersion: apps/v1
kind: Deployment
metadata:
  name: sf-backend
  labels:
    app: sf-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sf-backend
  template:
    metadata:
      labels:
        app: sf-backend
    spec:
      nodeSelector:
        role: backend
      containers:
        - name: sf-backend
          image: 809808214826.dkr.ecr.ap-northeast-2.amazonaws.com/sf-backend:b411b27cd6257bc5e07a2dcdfde0961d48b2f9dc
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: sf-backend-secrets
            - configMapRef:
                name: sf-backend-config
                
