apiVersion: apps/v1
kind: Deployment
metadata:
  name: sf-backend
  labels:
    app: sf-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sf-backend
  template:
    metadata:
      labels:
        app: sf-backend
    spec:
      nodeSelector:
        role: backend
      containers:
        - name: sf-backend
          image: 613307913976.dkr.ecr.ap-northeast-2.amazonaws.com/sf-backend:1c87863f19c08c25ce7e2b149cefd3b9d90f979a
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: sf-backend-secrets
            - configMapRef:
                name: sf-backend-config
                
