apiVersion: apps/v1
kind: Deployment
metadata:
  name: sf-backend
  labels:
    app: sf-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sf-backend
  template:
    metadata:
      labels:
        app: sf-backend
    spec:
      nodeSelector:
        role: backend
      containers:
        - name: sf-backend
          image: 613307913976.dkr.ecr.ap-northeast-2.amazonaws.com/sf-backend:462074514f046662d669915321a66776947a1f9f
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MARIADB_URL
              value: "jdbc:mysql://175.114.229.158:3306/factory-tycoon2"
            - name: MARIADB_USERNAME
              value: "root"
            - name: MARIADB_PASSWORD
              value: "pass"
            - name: AWS_REGION
              value: ap-northeast-2
            - name: AWS_DEFAULT_REGION
              value: ap-northeast-2
            - name: REDIS_HOST
              value: "175.114.229.158"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "pass"
            - name: JWT_SECRET_KEY
              value: "your-secret-key-change-this-in-production-min-256-bits"
            - name: JWT_ACCESS_TTL_MS
              value: "3600000"
            - name: JWT_REFRESH_TTL_MS
              value: "86400000"
            